jobs:
  - name: heartbeat_every_minute
    enabled: true
    strategy: cron
    cron:
      def: "* * * * *"
    nats:
      subject: heartbeat.every.minute
    data:
      foo: bar
  - name: heartbeat_every_two_minutes
    enabled: true
    strategy: cron
    cron:
      def: "*/2 * * * *"
    nats:
      subject: heartbeat.every.two_minutes
    data:
      foo: bar
  - name: heartbeat_every_five_minutes
    enabled: true
    strategy: cron
    cron:
      def: "*/5 * * * *"
    nats:
      subject: heartbeat.every.five_minutes
    data:
      foo: bar
