jobs:
  - name: heartbeat_every_minute
    enabled: true
    strategy: cron
    cron:
      def: "* * * * *"
    nats:
      subject: HeartbeatRequest
      data:
        name: every_minute
  - name: heartbeat_every_two_minutes
    enabled: true
    strategy: cron
    cron:
      def: "*/2 * * * *"
    nats:
      subject: HeartbeatRequest
      data:
        name: every_two_minutes
  - name: heartbeat_every_five_minutes
    enabled: true
    strategy: cron
    cron:
      def: "*/5 * * * *"
    nats:
      subject: HeartbeatRequest
      data:
        name: every_five_minutes
